### ISSUE TITLE
Update Footer and Action Button.

### ISSUE THREAD

**Issue by Vivek-Hotti** [Vivek-Hotti/NASA_pic-of-the-day#1]
The footer seems too minimal and boring. 
So create a new footer with as many links as you want.

Also, I'd like look to upgrade the looks of the button.

**Comment by Godwindaniel10** [comment]
Hi , i am godwin, i will love to work on this issue.

can i fork this?

**Comment by Vivek-Hotti** [comment]
Yeah! Go ahead!

**Comment by Godwindaniel10** [comment]
Ok 👍 , on it..

**Comment by Godwindaniel10** [comment]
Do you wish to add any links or anything at the footer?

**Comment by Vivek-Hotti** [comment]
Yes! Maybe you could add my Github profile link!

**Comment by Godwindaniel10** [comment]
i think you have your GitHub profile link active already.

i think we should add, your Twitter link, and i am adding a quote at the footer as well

**Comment by Vivek-Hotti** [comment]
Sounds good to me buddy 👍

**Comment by Godwindaniel10** [comment]
ok great, I will be needing your Twitter profile link

**Comment by Vivek-Hotti** [comment]
https://twitter.com/hotti_vivek 

here you go

**Comment by Godwindaniel10** [comment]
ok
