### ISSUE TITLE
Text and image wrapping not great.

### ISSUE THREAD

**Issue by Vivek-Hotti** [Vivek-Hotti/NASA_pic-of-the-day#3]
So sometimes, the last word of a sentence gets along with the image and gets dragged down with its height. Would like to prevent this from happening in the future.

An instance:

![image](https://user-images.githubusercontent.com/59518168/113978643-cd630380-9861-11eb-9731-6857405a5f9b.png)

**Comment by SajeelHassan** [comment]
I fixed it. Review and accept the pull request

**Comment by Vivek-Hotti** [comment]
LGTM! Thanks for your contribution.
